#import "/lib.typ": *
#title[Parsing of Rust]
= Parsing
#footnote[#a[Is there a library that lets you parse rust code? : r/rust][https://www.reddit.com/r/rust/comments/4dobqo/is_there_a_library_that_lets_you_parse_rust_code/]]
#footnote[#a[parsing - How to parse Rust code without using procedural macros? - Stack Overflow][https://stackoverflow.com/questions/57408862/how-to-parse-rust-code-without-using-procedural-macros]]
#footnote[#a[A Rust library to parse Rust code in order to determine the location of a definition of a given identifier? : r/rust][https://www.reddit.com/r/rust/comments/oms2rc/a_rust_library_to_parse_rust_code_in_order_to/]]
#footnote[#a[Where can I find a super simple rust parser? - The Rust Programming Language Forum][https://users.rust-lang.org/t/where-can-i-find-a-super-simple-rust-parser/104900]]
#footnote[#a[Is there a crate for parsing rust projects on a higher level for build scripts : r/rust][https://www.reddit.com/r/rust/comments/14ei5kw/is_there_a_crate_for_parsing_rust_projects_on_a/]]

- rustc
  - ```sh cargo rustc -- -Zunpretty=expanded```
    - `normal`, `identified`,
    - `expanded`, `expanded,identified`,
      - `#[cfg]` is expanded, but doc comments are kept.
      - #a[dtolnay/cargo-expand: Subcommand to show result of macro expansion][https://github.com/dtolnay/cargo-expand]
        - #q[Remove all `macro_rules`, doc attributes on statements]
          #footnote[#a[Fails to format doc comments on statements - Issue \#71 - dtolnay/cargo-expand][https://github.com/dtolnay/cargo-expand/issues/71]]
        - #strike[#a[Feature Request : output sources to folder - Issue \#174][https://github.com/dtolnay/cargo-expand/issues/174]]
          #footnote[#a[Correct way of expanding once and get code for each file separately - Issue \#227 - dtolnay/cargo-expand][https://github.com/dtolnay/cargo-expand/issues/227]]
    - `expanded,hygiene` (with internal representations),
    - AST
      - `ast-tree` (raw AST before expansion),
      - `ast-tree,expanded` (raw AST after expansion),
    - HIR
      #footnote[#a[The HIR (High-level IR) - Rust Compiler Development Guide][https://rustc-dev-guide.rust-lang.org/hir.html]]
      - `hir` (the HIR), `hir,identified`,
      - `hir,typed` (HIR with types for each node),
      - `hir-tree` (dump the raw HIR),
      - `thir-tree`, `thir-flat`,
    - `mir` (the MIR), or `mir-cfg` (graphviz formatted MIR)

- Clippy

- rust-analyzer
  - #a[`ide`][https://rust-lang.github.io/rust-analyzer/ide/]
  - #a[`ra_ap_parser`][https://docs.rs/ra_ap_parser/latest/ra_ap_parser/]

- #a[dtolnay/syn: Parser for Rust source code][https://github.com/dtolnay/syn]

  #q[Syn is ridiculously large in its full featured version. It also exports a ridiculous amount of metadata. Most crates have a relatively small public API, sometimes a couple of public functions, and once you get the public metadata, the compilation of dependencies is unblocked. Syn, by comparison, mostly consists of publuc API. Tons of structs, tons of functions, tons of impls.

  Syn is way more complex than required for Rust. It parses a much more complex language which covers all currently feasible paths of evolution. For example, it allows attributes literally everywhere, while on stable they are only allowed on items and blocks.

  Syn is also super slow, since it boxes everything. This may be an acceptable cost for the use case of macros, maybe even inevitable given the design of proc macros. However, it also means syn is at least 1-2 orders slower than it could be, making it a very poor fit for any kind of large-scale analysis of Rust code by the tooling.]
  #footnote[#a[Rust language parsers? Do you have any recommendations? : r/rust][https://www.reddit.com/r/rust/comments/xgvhcs/rust_language_parsers_do_you_have_any/]]

  #q[It will work fine until the user has `.rs` files lying around that aren't actually part of the module tree,
  or is `include!` ing generated files,
  or has functions that are annotated with your attribute that are cfg'd out,
  or has such functions generated by a macro, or....]
  #footnote[#a[How to parse the AST of an entire crate? : r/rust][https://www.reddit.com/r/rust/comments/11du0mh/how_to_parse_the_ast_of_an_entire_crate/]]

- #a[shepmaster/fuzzy-pickles: A Rust parser to power Strata Rust][https://github.com/shepmaster/fuzzy-pickles]

`syn` doesn't preserve locations,
`fuzzy-pickles` does.
#footnote[#a[Parse Rust source code and track line numbers - help - The Rust Programming Language Forum][https://users.rust-lang.org/t/parse-rust-source-code-and-track-line-numbers/12888]]

= Code generation
- #a[dtolnay/quote: Rust quasi-quoting][https://github.com/dtolnay/quote]

- #a[dtolnay/prettyplease: A minimal `syn` syntax tree pretty-printer][https://github.com/dtolnay/prettyplease]

- #a[rust-lang/rustfmt: Format Rust code][https://github.com/rust-lang/rustfmt]

  #q[Format using `rustfmt` instead of `prettyplease`. This is significantly
  slower, and less reliable on macro-generated code, but produces more
  aesthetic formatting when it works.]

See also #a[Constant Generation][Constant.typ].
